name: "post_encode_star_solo_gene_count_plots"
description: "Post plots of STAR solo generated gene count summary statistics"
url: "https://github.com/detrout/woldlab-rna-seq"
authors:
  - Diane Trout
input:
  - percent mitochondria plot
  - genes by count plot
  - counts violin plot
  - posted metadata file
output:
  - percent mitochondria upload marker log file
