channels:
  - conda-forge
  - https://woldlab.caltech.edu/~diane/conda/
dependencies:
  - woldlab-rna-seq==1.3.0
  - scanpy==1.9.3
  - matplotlib==3.7.1
  - pip
  - pip:
      - mex_gene_archive==0.2.2
