channels:
  - conda-forge
  - https://woldlab.caltech.edu/~diane/conda/
dependencies:
  - dask==2023.1.1
  - anndata==0.9.1
  - seaborn==0.12.2
  - woldlab-rna-seq==1.3.0
  - pip
  - pip:
      - mex_gene_archive==0.2.2
